domain_path: /home/usuario/Documents/pong_fpga/platform_pong/export/platform_pong/sw/standalone_microblaze_riscv_0
app_src_dir: /home/usuario/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
