#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 4

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_0_IS_DUAL 0x1
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x10
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_1_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_1_IS_DUAL 0x0
#define XPAR_AXI_GPIO_1_GPIO_WIDTH 0x5

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x5
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_2 */
#define XPAR_AXI_GPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_2_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_2_HIGHADDR 0x4002ffff
#define XPAR_AXI_GPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_2_IS_DUAL 0x0
#define XPAR_AXI_GPIO_2_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_2 */
#define XPAR_XGPIO_2_BASEADDR 0x40020000
#define XPAR_XGPIO_2_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x10
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_3 */
#define XPAR_AXI_GPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_3_BASEADDR 0x40030000
#define XPAR_AXI_GPIO_3_HIGHADDR 0x4003ffff
#define XPAR_AXI_GPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_3_IS_DUAL 0x0
#define XPAR_AXI_GPIO_3_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_3 */
#define XPAR_XGPIO_3_BASEADDR 0x40030000
#define XPAR_XGPIO_3_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x4
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a0ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x10

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_XSPI_0_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_STARTUP_BLOCK 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

/* Definitions for peripheral TOP_VGA_0 */
#define XPAR_TOP_VGA_0_BASEADDR 0xc0000000
#define XPAR_TOP_VGA_0_HIGHADDR 0xc003ffff

/* Canonical definitions for peripheral TOP_VGA_0 */
#define XPAR_TOP_VGA_0_BASEADDR 0xc0000000
#define XPAR_TOP_VGA_0_HIGHADDR 0xc003ffff

/*  BOARD definition */
#define XPS_BOARD_NEXYS-A7-100T

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0x87ffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x3fff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */